name: CI/CD Pipeline for Budibase Change Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Or the version required by your project

    - name: Install dependencies
      run: npm install

    - name: Run tests (if applicable)
      run: npm test # Only if you have tests defined

    - name: Deploy to production (or staging)
      run: |
        # Add your deployment script here, e.g., deploy to a cloud service or Budibase server
        echo "Deploying to production..."
