name: Deploy Budibase App

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use Node.js 18 or higher

      - name: Clear NPM cache
        run: npm cache clean --force

      - name: Install Budibase CLI
        run: |
          npm install -g @budibase/cli
          echo "Global NPM packages path: $(npm root -g)"  # Print the global NPM packages path
          echo "Installed Budibase CLI location: $(which bbb || echo 'bbb not found')"  # Check if bbb is installed
          echo "$(npm root -g)/bin" >> $GITHUB_PATH  # Add the correct global NPM binaries path to PATH
          echo "PATH: $PATH"  # Print the PATH to verify it includes the global NPM binaries
          bbb --version  # Verify installation by checking the version

      - name: Deploy to Budibase
        env:
          BUDIBASE_API_KEY: ${{ secrets.BUDIBASE_API_KEY }}  # Use the secret
          BUDIBASE_APP_ID: ${{ secrets.BUDIBASE_APP_ID }}    # Use the secret
        run: |
          bbb auth --api-key $BUDIBASE_API_KEY
          bbb apps publish --appId $BUDIBASE_APP_ID
